ENV['TWITTER_CLIENT_KEY'] = "XXXXXXXX"
ENV['TWITTER_CLIENT_SECRET'] = "XXXXXXXXX"

ENV['TWITTER_USER_KEY'] = "XXXXXXXXX"
ENV['TWITTER_USER_SECRET'] = "XXXXXXXXX"

ENV['FLICKR_API_KEY'] = "XXXXXXXXXXXXXXXXXXXX"
ENV['FLICKR_API_SECRET'] = "XXXXXXXXXXXXXXXXXXXXXXXX"
